### ISSUE TITLE
"?" in reminder text isn't escaped proper

### ISSUE THREAD

**Issue by ErgoAsciiCat** [Tsubashi/botc_tokens#1]
When using the botc_tokens create command on Windows [Version 10.0.22631.3155]  the "?" field in the reminder token text of Amnesiac creates an exception. Both "?" and "\u003F" in the reminders field create said exception.
```
Finding Roles...
0:00:00 ---------------------------------------- Creating Tokens... -:--:--
  |- Creating Token for: Amnesiac .
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Scripts\botc_tokens.exe\__main__.py", line 7, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\botc_tokens\__main__.py", line 57, in main
    retcode = allowed_commands[args.command][0]()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\botc_tokens\commands\create.py", line 138, in run
    reminder.save(filename=reminder_output_path)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\wand\image.py", line 10214, in save
    self.raise_exception()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\wand\resource.py", line 225, in raise_exception
    raise e
wand.exceptions.CoderError: WriteBlob Failed `tokens\4a - Kickstarter Experimental\townsfolk\Amnesiac-Reminder-?.png' @ error/png.c/MagickPNGErrorHandler/1492
```

**Comment by Tsubashi** [comment]
Ah, that makes sense. Windows has different restrictions on filenames than the Mac I develop on. I don't have a windows computer handy to test on, but I've pushed a commit to dev that should take care of that. I'll close the issue if you can confirm it fixes it, or the next time I have a PC handy. 

Thanks for reporting it!

**Comment by Tsubashi** [comment]
Just tested it at it looks like it is fixed in the latest release. Let me know if you run into anything else!
